apiVersion: v1
kind: Service
metadata:
  name: vexgen-backend-svc
  labels:
    app: vexgen-backend
spec:
  type: ClusterIP
  selector:
    app: vexgen-backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
