apiVersion: apps/v1
kind: Deployment
metadata:
  name: vexgen-backend-d
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vexgen-backend
  template:
    metadata:
      labels:
        app: vexgen-backend
    spec:
      containers:
        - name: vexgen-backend
          image: germanmt/vexgen-backend:0.2.26
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "2"
            requests:
              memory: "100Mi"
              cpu: "0.5"
          envFrom:
            - configMapRef:
                name: backend-config-map
            - secretRef:
                name: backend-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
