FROM node:lts-alpine AS build-stage

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

RUN npm run build

FROM nginx:1.26.2-alpine AS production-stage

COPY --from=build-stage /frontend/build/ /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/nginx.conf

EXPOSE 90

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]