FROM python:3.13.1-alpine

WORKDIR /backend

COPY /backend/requirements.txt ./

RUN apk add --no-cache \
    curl \
    gcc \
    musl-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del gcc musl-dev

ENV GIT_PYTHON_REFRESH=quiet

EXPOSE 8000

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/backend/app" ]