apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      name: mongodb
  serviceName: mongodb-svc
  replicas: 3
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:7.0.16
          command:
            - mongod
          args:
            - --bind_ip=0.0.0.0
            - --replSet=rs0
            - --dbpath=/data/db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume
      spec:
        storageClassName: mongodb-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
