name: Publish GitHub Release

on:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push GitHub Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Automated Version Bump
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{secrets.GIT_TOKEN}}
          tag: ${{github.ref_name}}
          writeToFile: false
          excludeTypes: other

      - name: Get variables
        id: get_variables
        run: |
          echo "{VERSION}={${GITHUB_REF/refs\/tags\//}}"  >> $GITHUB_OUTPUT
          echo "{IS_PRERELEASE}={"${{contains(github.ref, 'dev')}}"}"  >> $GITHUB_OUTPUT

      - name: Publish release github
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.GIT_TOKEN}}
          prerelease: ${{steps.get_variables.outputs.IS_PRERELEASE}}
          tag_name: ${{steps.get_variables.outputs.VERSION}}
          body: ${{steps.changelog.outputs.changes}}
